ALTER TABLE f_genre ADD scheduler_code varchar(45) NULL DEFAULT NULL;


UPDATE f_genre SET scheduler_code='MuAmbient' WHERE genre=111;
UPDATE f_genre SET scheduler_code='MuBassMsic' WHERE genre=159;
UPDATE f_genre SET scheduler_code='MuChanson' WHERE genre=152;
UPDATE f_genre SET scheduler_code='MuClassic' WHERE genre=153;
UPDATE f_genre SET scheduler_code='MuCntryBlu' WHERE genre=154;
UPDATE f_genre SET scheduler_code='MuDwnTempo' WHERE genre=161;
UPDATE f_genre SET scheduler_code='MuElectro' WHERE genre=4;
UPDATE f_genre SET scheduler_code='MuExp' WHERE genre=58;
UPDATE f_genre SET scheduler_code='MuExtreme' WHERE genre=163;
UPDATE f_genre SET scheduler_code='MuFolk' WHERE genre=155;
UPDATE f_genre SET scheduler_code='MuFR' WHERE genre=164;
UPDATE f_genre SET scheduler_code='MuFunkSoul' WHERE genre=156;
UPDATE f_genre SET scheduler_code='MuGOLD' WHERE genre=165;
UPDATE f_genre SET scheduler_code='MuGroovRnB' WHERE genre=166;
UPDATE f_genre SET scheduler_code='MuHipHop' WHERE genre=157;
UPDATE f_genre SET scheduler_code='MuHouse' WHERE genre=142;
UPDATE f_genre SET scheduler_code='MuIndie' WHERE genre=131;
UPDATE f_genre SET scheduler_code='MuInstru' WHERE genre=167;
UPDATE f_genre SET scheduler_code='MuJazz' WHERE genre=23;
UPDATE f_genre SET scheduler_code='MuLocal' WHERE genre=168;
UPDATE f_genre SET scheduler_code='MuMetal' WHERE genre=72;
UPDATE f_genre SET scheduler_code='MuNoise' WHERE genre=63;
UPDATE f_genre SET scheduler_code='MuPop' WHERE genre=2;
UPDATE f_genre SET scheduler_code='MuPunk' WHERE genre=123;
UPDATE f_genre SET scheduler_code='MuRap' WHERE genre=82;
UPDATE f_genre SET scheduler_code='MuReggDub' WHERE genre=3;
UPDATE f_genre SET scheduler_code='MuReprise' WHERE genre=172;
UPDATE f_genre SET scheduler_code='MuRock' WHERE genre=1;
UPDATE f_genre SET scheduler_code='MuTechno' WHERE genre=69;
UPDATE f_genre SET scheduler_code='MuWorldLat' WHERE genre=158;
UPDATE f_genre SET scheduler_code='Poesie' WHERE genre=171;
UPDATE f_genre SET scheduler_code='MuLong' WHERE genre=169;
UPDATE f_genre SET scheduler_code='MuCourt' WHERE genre=160;
UPDATE f_genre SET scheduler_code='MuMathPost' WHERE genre=170;
